# Generated by Django 4.2.2 on 2023-06-11 21:13

import custom_auth.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理者ステータス')),
                ('is_member', models.BooleanField(default=False, verbose_name='会員ステータス')),
                ('is_active', models.BooleanField(default=False, verbose_name='アカウントステータス')),
                ('groups', models.ManyToManyField(blank=True, help_text='Specific Groups for this user.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='Group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'verbose_name_plural': 'ユーザ',
            },
        ),
        migrations.CreateModel(
            name='SignUpKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('key', models.UUIDField(default=uuid.uuid4, verbose_name='認証キー')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='コメント')),
                ('expired_at', models.DateTimeField(default=custom_auth.models.sign_up_key_expire_date, verbose_name='有効期限')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
            ],
            options={
                'verbose_name': 'サインアップ用のKey',
                'verbose_name_plural': 'サインアップ用のKey',
            },
        ),
        migrations.CreateModel(
            name='UserActivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Active token')),
                ('expired_at', models.DateTimeField(default=custom_auth.models.user_activate_expire_date, verbose_name='有効期限')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activate用のToken',
                'verbose_name_plural': 'Activate用のToken',
            },
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=False, verbose_name='アカウントステータス')),
                ('comment', models.CharField(blank=True, default='', max_length=250, verbose_name='comment')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
            },
            bases=('auth.group',),
        ),
    ]
