# Generated by Django 4.2.2 on 2023-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_user_stripe_customer_id_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有効期限'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_charge',
            field=models.BooleanField(default=False, verbose_name='課金'),
        ),
        migrations.AddField(
            model_name='group',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe(CusID)'),
        ),
        migrations.AddField(
            model_name='group',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe(SubID)'),
        ),
    ]
