# Generated by Django 4.2.4 on 2023-08-29 03:44

import custom_auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_group_expired_at_group_is_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('token', models.CharField(max_length=100, verbose_name='token')),
                ('expired_at', models.DateTimeField(default=custom_auth.models.email_verify_expire_date, verbose_name='有効期限')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail用のVerify',
                'verbose_name_plural': 'E-Mail用のVerify',
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('secret', models.CharField(max_length=100, verbose_name='secret')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP Device',
                'verbose_name_plural': 'TOTP Device',
            },
        ),
    ]
