# Generated by Django 4.2.2 on 2023-07-02 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('start_ip', models.GenericIPAddressField(verbose_name='Start IP')),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)], verbose_name='Size')),
                ('gateway_ip', models.GenericIPAddressField(verbose_name='Gateway IP(Local)')),
                ('global_ip', models.GenericIPAddressField(verbose_name='Global IP')),
                ('global_port', models.IntegerField(default=51820, verbose_name='Global Port')),
                ('mgmt_ip', models.GenericIPAddressField(verbose_name='Management IP')),
                ('mgmt_port', models.IntegerField(default=8080, verbose_name='Management Port')),
                ('private_key', models.CharField(max_length=250, verbose_name='秘密鍵')),
                ('public_key', models.CharField(max_length=250, verbose_name='公開鍵')),
            ],
            options={
                'verbose_name': 'Wireguardサーバ',
                'verbose_name_plural': 'Wireguardサーバ',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPv4')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPv6')),
                ('public_key', models.CharField(max_length=250, verbose_name='公開鍵')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wireguard.server')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wireguard_service', to='service.service')),
            ],
            options={
                'verbose_name': 'Wireguardサービス',
                'verbose_name_plural': 'Wireguardサービス',
            },
        ),
    ]
