# Generated by Django 4.2.2 on 2023-06-17 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dsbd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('type1', models.CharField(max_length=200, verbose_name='type1')),
                ('type2', models.CharField(blank=True, default='', max_length=200, verbose_name='type2')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', dsbd.models.MediumTextField(blank=True, default='', verbose_name='内容')),
                ('comment', models.CharField(default='', max_length=250, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'チケットテンプレート',
                'verbose_name_plural': 'チケットテンプレート',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', dsbd.models.MediumTextField(blank=True, default='', verbose_name='内容')),
                ('is_solved', models.BooleanField(default=False, verbose_name='解決済み')),
                ('is_approve', models.BooleanField(default=False, verbose_name='承認済み')),
                ('is_reject', models.BooleanField(default=False, verbose_name='拒否済み')),
                ('from_admin', models.BooleanField(default=False, verbose_name='運営委員から起票')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'チケット',
                'verbose_name_plural': 'チケット',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日')),
                ('body', dsbd.models.MediumTextField(blank=True, default='', verbose_name='内容')),
                ('is_admin', models.BooleanField(default=False, verbose_name='運営委員がコメント')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customgroup')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'チャット',
                'verbose_name_plural': 'チャット',
            },
        ),
    ]
