# Generated by Django 4.2.3 on 2023-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='number',
            field=models.IntegerField(auto_created=True, default=100, verbose_name='順序'),
        ),
    ]
